# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Feature Push

on:
  push:
    branches: [ feature ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build and test with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build test

    - name: Get Current Version
      uses: gradle/gradle-build-action@v2
      with:
        arguments: cV

    - name: Release
      uses: gradle/gradle-build-action@v2
      with:
        arguments: release -Prelease.incrementer=incrementMinor

    - name: Get Current Version
      uses: gradle/gradle-build-action@v2
      with:
        arguments: cV


#    - name: Publish Pact contract
#      uses: gradle/gradle-build-action@v2
#      with:
#        arguments: pactPublish -Ppact.provider.branch=$GITHUB_REF_NAME

#    - name: Verify Pacts
#      uses: gradle/gradle-build-action@v2
#      with:
#        arguments: pactVerify
