name: Feature Push

on:
  push:
    branches: [ feature ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Gradle - build test
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build test

    - name: Publish Pact contract
      uses: gradle/gradle-build-action@v2
      with:
        arguments: pactPublish
  deploy:
    runs-on: ubuntu-latest
    environment: develop
