name: PR to main

on:
  pull_request:
    types: [ closed ]
    branches: [ main ]

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Release
        uses: gradle/gradle-build-action@v2
        with:
          arguments: release -Prelease.incrementer=incrementMinor